// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicoOportunidades.Data;

#nullable disable

namespace ServicoOportunidades.Migrations
{
    [DbContext(typeof(OportunidadesContext))]
    partial class OportunidadesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ServicoOportunidades.Models.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AreaM2")
                        .HasColumnType("REAL");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoSimples")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepresentanteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusFicha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TituloObra")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ValorEstimado")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Fichas");
                });
#pragma warning restore 612, 618
        }
    }
}
